version: "2"
services:
    postgres:
        image: "postgres:9.5-alpine"
        container_name: postgres
        ports:
            - "5439:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: test
